/**
 * Rewrites the source models into headset-sized GLBs.
 *
 * The downloads in `public/gltf` are desktop-renderer assets and their texture
 * budget is the single thing that decides whether this app runs on a Quest at
 * all. `bmw_m3_gtr_e46_black.glb` alone ships forty 4096x4096 maps: 3.4 GB once
 * the GPU has them as RGBA8 with mips, against roughly 1 GB of headroom for the
 * whole page. The carousel measured 4.1 GB in total. That is the freeze.
 *
 * Resolution is what costs VRAM, and it costs it as the square: dropping a 4096
 * map to 1024 is a 16x saving before a single triangle is drawn. Colour maps are
 * capped harder than data maps because a car is read from two metres away, not
 * from the paint booth.
 *
 * What this deliberately does NOT do is touch geometry. Meshes here are cheap
 * next to their textures (570k triangles across the whole catalog), and the two
 * models authored as triangle strips would need re-indexing to be safe.
 *
 * Outputs are derived files: generated into `public/gltf/optimized/`, ignored by
 * git, and regenerated by predev/prebuild exactly like `playlist.json`. Re-runs
 * are incremental — a model is skipped when its output is newer than its input.
 *
 * A further ~8x is available by encoding to KTX2/BasisU, which stays compressed
 * in VRAM and which IWSDK's loader already supports. It needs a native encoder
 * binary (`toktx`, or a native gltfpack build); the npm build of gltfpack is
 * compiled without BasisU. Left as a follow-up.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const GLTF_DIR = join(PROJECT_ROOT, 'public', 'gltf');
const OUT_DIR = join(GLTF_DIR, 'optimized');

/**
 * Longest edge, in pixels, for maps the eye reads as detail — base colour and
 * emissive. 1024 is the point where a 4.6 m car at arm's length stops gaining.
 */
const COLOR_MAX = 1024;
/**
 * Normal, metallic-roughness and occlusion maps. These modulate shading rather
 * than being looked at, so half the colour budget is invisible in practice and
 * saves three quarters of the memory.
 */
const DATA_MAX = 512;
/** WebP quality. Data maps get more because banding in a normal map shows. */
const COLOR_QUALITY = 82;
const DATA_QUALITY = 90;

const GLB_MAGIC = 0x46546c67;
const CHUNK_JSON = 0x4e4f534a;
const CHUNK_BIN = 0x004e4942;

/** Models to process: everything the manifest can point at. */
function collectInputs() {
  const inputs = [];
  const carsDir = join(GLTF_DIR, 'cars');
  for (const entry of readdirSync(carsDir, { withFileTypes: true })) {
    if (entry.isFile() && extname(entry.name).toLowerCase() === '.glb') {
      inputs.push({ file: join(carsDir, entry.name), out: `cars/${stem(entry.name)}.glb` });
    } else if (entry.isDirectory()) {
      // Unpacked glTF (separate .bin + texture folder). Emit a single GLB so the
      // headset makes one request instead of twenty-three.
      const gltf = readdirSync(join(carsDir, entry.name)).find(
        (name) => extname(name).toLowerCase() === '.gltf',
      );
      if (gltf != null) {
        inputs.push({
          file: join(carsDir, entry.name, gltf),
          out: `cars/${entry.name}.glb`,
        });
      }
    }
  }

  const garageDir = join(GLTF_DIR, 'garage');
  const garage = readdirSync(garageDir).find(
    (name) => extname(name).toLowerCase() === '.gltf',
  );
  if (garage != null) {
    inputs.push({ file: join(garageDir, garage), out: 'garage.glb' });
  }
  const soundSystem = join(GLTF_DIR, 'sound_system.glb');
  if (exists(soundSystem)) {
    inputs.push({ file: soundSystem, out: 'sound_system.glb' });
  }
  return inputs;
}

// --- glTF/GLB container ------------------------------------------------------

/** Read either container into `{ json, bin }` with every buffer resolved. */
function readModel(file) {
  const buf = readFileSync(file);
  if (extname(file).toLowerCase() === '.glb') {
    const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
    if (view.getUint32(0, true) !== GLB_MAGIC) {
      throw new Error('not a GLB');
    }
    const total = view.getUint32(8, true);
    let offset = 12;
    let json = null;
    let bin = Buffer.alloc(0);
    while (offset < total) {
      const length = view.getUint32(offset, true);
      const type = view.getUint32(offset + 4, true);
      const start = offset + 8;
      if (type === CHUNK_JSON) {
        json = JSON.parse(buf.subarray(start, start + length).toString('utf8'));
      } else if (type === CHUNK_BIN) {
        bin = buf.subarray(start, start + length);
      }
      offset = start + length;
    }
    return { json, bin };
  }

  const json = JSON.parse(buf.toString('utf8'));
  // Separate .bin files (and data: URIs) are concatenated into one buffer, and
  // every bufferView is rebased onto it.
  const parts = [];
  const bases = [];
  let cursor = 0;
  for (const buffer of json.buffers ?? []) {
    const bytes = buffer.uri == null ? Buffer.alloc(0) : readUri(buffer.uri, file);
    bases.push(cursor);
    parts.push(bytes);
    cursor += align4(bytes.length);
    if (bytes.length % 4 !== 0) {
      parts.push(Buffer.alloc(4 - (bytes.length % 4)));
    }
  }
  for (const bufferView of json.bufferViews ?? []) {
    bufferView.byteOffset = (bufferView.byteOffset ?? 0) + bases[bufferView.buffer ?? 0];
    bufferView.buffer = 0;
  }
  return { json, bin: Buffer.concat(parts) };
}

function readUri(uri, fromFile) {
  if (uri.startsWith('data:')) {
    return Buffer.from(uri.slice(uri.indexOf(',') + 1), 'base64');
  }
  return readFileSync(resolve(dirname(fromFile), decodeURIComponent(uri)));
}

/**
 * Rebuild the binary chunk so bufferViews stay contiguous and correctly aligned.
 *
 * Image views are replaced with their re-encoded bytes; every other view is
 * copied verbatim, which is what keeps accessor `byteOffset`s and `byteStride`
 * valid without rewriting a single accessor.
 */
function writeGLB(json, bin, replacements) {
  const parts = [];
  let cursor = 0;
  for (let i = 0; i < (json.bufferViews ?? []).length; i += 1) {
    const view = json.bufferViews[i];
    const replacement = replacements.get(i);
    const bytes =
      replacement ??
      bin.subarray(view.byteOffset ?? 0, (view.byteOffset ?? 0) + view.byteLength);
    const padding = align4(cursor) - cursor;
    if (padding > 0) {
      parts.push(Buffer.alloc(padding));
      cursor += padding;
    }
    view.byteOffset = cursor;
    view.byteLength = bytes.length;
    view.buffer = 0;
    if (replacement != null) {
      // An image view carries no vertex layout; a stale stride would be invalid.
      delete view.byteStride;
    }
    parts.push(bytes);
    cursor += bytes.length;
  }
  const binChunk = Buffer.concat(parts);
  const binPadded = Buffer.concat([binChunk, Buffer.alloc(align4(binChunk.length) - binChunk.length)]);

  json.buffers = [{ byteLength: binChunk.length }];
  const jsonChunk = Buffer.from(JSON.stringify(json), 'utf8');
  const jsonPadded = Buffer.concat([
    jsonChunk,
    Buffer.alloc(align4(jsonChunk.length) - jsonChunk.length, 0x20),
  ]);

  const header = Buffer.alloc(12);
  header.writeUInt32LE(GLB_MAGIC, 0);
  header.writeUInt32LE(2, 4);
  header.writeUInt32LE(12 + 8 + jsonPadded.length + 8 + binPadded.length, 8);

  const jsonHeader = Buffer.alloc(8);
  jsonHeader.writeUInt32LE(jsonPadded.length, 0);
  jsonHeader.writeUInt32LE(CHUNK_JSON, 4);

  const binHeader = Buffer.alloc(8);
  binHeader.writeUInt32LE(binPadded.length, 0);
  binHeader.writeUInt32LE(CHUNK_BIN, 4);

  return Buffer.concat([header, jsonHeader, jsonPadded, binHeader, binPadded]);
}

// --- texture classification --------------------------------------------------

/**
 * Decide each image's budget from how the materials actually sample it.
 *
 * Colour wins ties: an image used as both base colour and roughness has to
 * satisfy the eye, and the shading channel will not miss the extra pixels.
 */
function classifyImages(json) {
  const roles = new Map();
  const mark = (textureIndex, role) => {
    const texture = json.textures?.[textureIndex?.index ?? -1];
    const source = texture?.source ?? texture?.extensions?.EXT_texture_webp?.source;
    if (source == null) {
      return;
    }
    if (role === 'color' || !roles.has(source)) {
      roles.set(source, role);
    }
  };

  for (const material of json.materials ?? []) {
    const pbr = material.pbrMetallicRoughness ?? {};
    mark(pbr.baseColorTexture, 'color');
    mark(material.emissiveTexture, 'color');
    mark(pbr.metallicRoughnessTexture, 'data');
    mark(material.normalTexture, 'data');
    mark(material.occlusionTexture, 'data');
    for (const extension of Object.values(material.extensions ?? {})) {
      for (const value of Object.values(extension ?? {})) {
        if (value != null && typeof value === 'object' && 'index' in value) {
          mark(value, 'data');
        }
      }
    }
  }
  return roles;
}

// --- per-model pass ----------------------------------------------------------

async function optimize(input) {
  const { json, bin } = readModel(input.file);
  const roles = classifyImages(json);
  const replacements = new Map();
  /** Encoded output deduped by content: these models repeat maps constantly. */
  const encoded = new Map();

  let before = 0;
  let after = 0;

  for (let i = 0; i < (json.images ?? []).length; i += 1) {
    const image = json.images[i];
    let source;
    if (image.bufferView != null) {
      const view = json.bufferViews[image.bufferView];
      source = bin.subarray(view.byteOffset ?? 0, (view.byteOffset ?? 0) + view.byteLength);
    } else if (image.uri != null) {
      source = readUri(image.uri, input.file);
    } else {
      continue;
    }

    const role = roles.get(i) ?? 'data';
    const limit = role === 'color' ? COLOR_MAX : DATA_MAX;
    const quality = role === 'color' ? COLOR_QUALITY : DATA_QUALITY;

    const meta = await sharp(source).metadata();
    before += vramBytes(meta.width, meta.height);

    const key = `${sha(source)}:${limit}:${quality}`;
    let output = encoded.get(key);
    if (output == null) {
      const pipeline = sharp(source, { failOn: 'none' });
      if (Math.max(meta.width, meta.height) > limit) {
        // `fit: inside` keeps the aspect ratio, so UVs stay valid, and both
        // edges land on a power of two because the sources already are.
        pipeline.resize({ width: limit, height: limit, fit: 'inside', withoutEnlargement: true });
      }
      output = {
        bytes: await pipeline.webp({ quality, effort: 4 }).toBuffer(),
      };
      const outMeta = await sharp(output.bytes).metadata();
      output.width = outMeta.width;
      output.height = outMeta.height;
      encoded.set(key, output);
    }
    after += vramBytes(output.width, output.height);

    // Every image ends up as a bufferView so the result is one self-contained
    // file, whether the input embedded its images or not.
    let viewIndex = image.bufferView;
    if (viewIndex == null) {
      viewIndex = json.bufferViews.length;
      json.bufferViews.push({ buffer: 0, byteOffset: 0, byteLength: 0 });
      delete image.uri;
      image.bufferView = viewIndex;
    }
    replacements.set(viewIndex, output.bytes);
    image.mimeType = 'image/webp';
  }

  // Three.js reads WebP through the standard image path, but a glTF that embeds
  // it must declare the extension or strict validators reject the file.
  if (replacements.size > 0) {
    json.extensionsUsed = [...new Set([...(json.extensionsUsed ?? []), 'EXT_texture_webp'])];
    for (const texture of json.textures ?? []) {
      if (texture.source != null) {
        texture.extensions = { ...texture.extensions, EXT_texture_webp: { source: texture.source } };
      }
    }
  }

  const glb = writeGLB(json, bin, replacements);
  const outFile = join(OUT_DIR, input.out);
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, glb);

  return {
    name: input.out,
    // For unpacked glTF the .gltf itself is a rounding error; the .bin and the
    // texture folder are the payload, so measure what the headset would fetch.
    diskBefore:
      extname(input.file).toLowerCase() === '.glb'
        ? statSync(input.file).size
        : sizeUnder(dirname(input.file)),
    diskAfter: glb.length,
    vramBefore: before,
    vramAfter: after,
  };
}

// --- helpers -----------------------------------------------------------------

/** RGBA8 plus a full mip chain — what the driver actually allocates. */
function vramBytes(width, height) {
  return (width ?? 0) * (height ?? 0) * 4 * 1.3333;
}
const align4 = (n) => (n + 3) & ~3;
const sha = (buf) => createHash('sha1').update(buf).digest('hex');
const stem = (name) => name.slice(0, -extname(name).length);
const mb = (bytes) => `${(bytes / 1048576).toFixed(1)} MB`;

function exists(file) {
  try {
    statSync(file);
    return true;
  } catch {
    return false;
  }
}

/**
 * Skip work already done. Compares against every sibling file for unpacked glTF,
 * so editing one texture in a folder still triggers a rebuild.
 */
function isFresh(input) {
  const outFile = join(OUT_DIR, input.out);
  if (!exists(outFile)) {
    return false;
  }
  const outTime = statSync(outFile).mtimeMs;
  const dir = dirname(input.file);
  const newest = extname(input.file).toLowerCase() === '.glb'
    ? statSync(input.file).mtimeMs
    : newestUnder(dir);
  return outTime > newest;
}

function newestUnder(dir) {
  let newest = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    newest = Math.max(newest, entry.isDirectory() ? newestUnder(path) : statSync(path).mtimeMs);
  }
  return newest;
}

function sizeUnder(dir) {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    total += entry.isDirectory() ? sizeUnder(path) : statSync(path).size;
  }
  return total;
}

// --- entry point -------------------------------------------------------------

const force = process.argv.includes('--force');
mkdirSync(OUT_DIR, { recursive: true });

const inputs = collectInputs();
const results = [];
let skipped = 0;

for (const input of inputs) {
  if (!force && isFresh(input)) {
    skipped += 1;
    continue;
  }
  process.stdout.write(`[models] ${input.out} ... `);
  try {
    const result = await optimize(input);
    results.push(result);
    console.log(
      `${mb(result.diskBefore)} -> ${mb(result.diskAfter)} on disk, ` +
        `${mb(result.vramBefore)} -> ${mb(result.vramAfter)} VRAM`,
    );
  } catch (error) {
    console.log(`FAILED (${error.message})`);
    process.exitCode = 1;
  }
}

if (results.length > 0) {
  const vramBefore = results.reduce((sum, r) => sum + r.vramBefore, 0);
  const vramAfter = results.reduce((sum, r) => sum + r.vramAfter, 0);
  console.log(
    `[models] ${results.length} rebuilt, ${skipped} up to date — ` +
      `texture VRAM ${mb(vramBefore)} -> ${mb(vramAfter)}`,
  );
} else {
  console.log(`[models] ${skipped} model(s) up to date.`);
}
